export const BARANGAYS = [
  'Anon',
  'Apalit',
  'Basa Air Base',
  'Benedicto',
  'Bodega',
  'Cabangcalan',
  'Calantas',
  'Carmencita',
  'Consuelo',
  'Dampe',
  'Del Carmen',
  'Fortuna',
  'Gutad',
  'Mabical',
  'Maligaya',
  'Mawacat',
  'Nabuclod',
  'Pabanlag',
  'Paguiruan',
  'Palmayo',
  'Pandaguirig',
  'Población',
  'San Antonio',
  'San Isidro',
  'San Jose',
  'San Nicolas',
  'San Ramon',
  'San Roque',
  'Santa Monica',
  'Santo Rosario(Malabo)',
  'Solib',
  'Valdez'
] as const;

export type Barangay = typeof BARANGAYS[number];
